FROM registry.fedoraproject.org/fedora:latest

VOLUME /build
WORKDIR /build
ENV FLATPAK_GL_DRIVERS=dummy

RUN dnf -y update && \
    dnf install -y flatpak flatpak-builder librsvg ostree fuse elfutils \
    dconf git bzr xorg-x11-server-Xvfb dbus-x11 && \
    dnf clean all

RUN flatpak remote-add flathub https://dl.flathub.org/repo/flathub.flatpakrepo && \
    flatpak remote-add gnome-nightly https://sdk.gnome.org/gnome-nightly.flatpakrepo
# RUN flatpak remote-add freedesktop-staging https://cache.sdk.freedesktop.org/freedesktop-sdk.flatpakrepo

# Add a machine-id as specified in the freedesktop spec:
# https://www.freedesktop.org/software/systemd/man/machine-id.html
# gnome-builder test suite depends on this
RUN cat /dev/urandom | tr -dc a-f0-9 | head -c32 > /etc/machine-id && echo "" >> /etc/machine-id

