FROM registry.fedoraproject.org/fedora:latest

VOLUME /build
WORKDIR /build
ENV FLATPAK_GL_DRIVERS=dummy

RUN dnf -y update && \
    dnf install -y flatpak ostree fuse elfutils \
    dconf git bzr xorg-x11-server-Xvfb dbus-x11

# Temporary pin flatpak-builder
RUN curl -o flatpak-builder-1.0.2-1.fc29.x86_64.rpm 'https://kojipkgs.fedoraproject.org//packages/flatpak-builder/1.0.2/1.fc29/x86_64/flatpak-builder-1.0.2-1.fc29.x86_64.rpm' && \
    dnf install -y flatpak-builder-1.0.2-1.fc29.x86_64.rpm && \
    dnf clean all

RUN flatpak remote-add flathub https://dl.flathub.org/repo/flathub.flatpakrepo && \
    flatpak remote-add gnome-nightly https://sdk.gnome.org/gnome-nightly.flatpakrepo
# RUN flatpak remote-add freedesktop-staging https://cache.sdk.freedesktop.org/freedesktop-sdk.flatpakrepo

# Add a machine-id as specified in the freedesktop spec:
# https://www.freedesktop.org/software/systemd/man/machine-id.html
# gnome-builder test suite depends on this
RUN cat /dev/urandom | tr -dc a-f0-9 | head -c32 > /etc/machine-id && echo "" >> /etc/machine-id

