#!/usr/bin/env python3

# The latest version of this script can be found at
# https://gitlab.gnome.org/GNOME/gnome-runtime-images

import gi
gi.require_version('Json', '1.0')

from gi.repository import Json
from ruamel import yaml
import argparse
import os, sys

from contextlib import contextmanager

def rewrite_json_manifest(args):
    with open(args.flatpak_manifest) as f:
        data = Json.from_string(f.read())

    mods = data.get_object().get_array_member('modules')
    for i in range(mods.get_length()):
        mod = mods.get_element(i)
        if mod.get_node_type() != Json.NodeType.OBJECT:
            continue
        mod = mod.get_object()

        if mod.get_string_member('name') == args.module_name:
            sources = mod.get_array_member('sources')
            new_sources = Json.Array()
            for i in range(sources.get_length()):
                if sources.get_object_element(i).get_string_member('type') != 'git':
                    new_sources.add_object_element(sources.get_object_element(i))
                    continue

                path = os.path.relpath('.', os.path.dirname(args.flatpak_manifest))
                new_sources.add_element(Json.from_string('{"type": "dir", "path": "%s"}' % path))

            mod.set_array_member('sources', new_sources)

            if args.config_opt:
                newconfig = Json.Array.sized_new(len(args.config_opt))
                for arg in args.config_opt:
                    newconfig.add_string_element(arg)
                mod.set_array_member('config-opts', newconfig)

    with open(args.flatpak_manifest, 'w') as f:
        f.write(Json.to_string(data, True))

def rewrite_yaml_manifest(args):
    with open(args.flatpak_manifest) as f:
        data = yaml.round_trip_load(f, preserve_quotes=True)

    for mod in data['modules']:
        if not isinstance(mod, dict):
            continue

        if mod['name'] == args.module_name:
            for i in range(len(mod['sources'])):
                if mod['sources'][i]['type'] != 'git':
                    continue
                path = os.path.relpath('.', os.path.dirname(args.flatpak_manifest))
                mod['sources'][i] = {'type': 'dir', 'path': path}

                if args.config_opt:
                    mod['config-opts'] = args.config_opt

    with open(args.flatpak_manifest, 'w') as f:
        yaml.round_trip_dump(data, f)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Prepare a flatpak manifest for CI execution')
    parser.add_argument('flatpak_manifest', help='filename of the flatpak manifest (JSON or YAML)')
    parser.add_argument('module_name', help='name of the main module in the manifest')
    parser.add_argument('config_opt', nargs='*', help='replacement values for config-opts of main module')

    args = parser.parse_args()
    if args.flatpak_manifest.endswith('.json'):
        rewrite_json_manifest(args)
    else:
        rewrite_yaml_manifest(args)
